export const FETCH_FAVOURITES = "FETCH_FAVOURITES";
export const ADD_TO_FAVOURITE = "ADD_FAVOURITE";
export const REMOVE_FROM_FAVOURITE = "REMOVE_FAVOURITE";
export const FETCH_MOVIES = "FETCH_MOVIES";
export const FETCH_MOVIE_DETAILS = "FETCH_MOVIE_DETAILS";
export const SEARCH_MOVIE = "SEARCH_MOVIE";
export const MOVIES_ARE_LOADING = "MOVIES_ARE_LOADING";
export const FETCH_MOVIES_SUCCESSED = "FETCH_MOVIES_SUCCESSED";
export const FETCH_MOVIES_FAILED = "FETCH_MOVIES_FAILED";

export const FETCH_GENRES_SUCCESSED = "FETCH_GENRES_SUCCESSED";
export const FETCH_GENRES_FAILED = "FETCH_GENRES_FAILED";
export const GENRES_ARE_LOADING = "GENRES_ARE_LOADING";
